### ISSUE TITLE
Add support for different Gui Icons

### ISSUE THREAD

**Issue by clementleger** [calaos/calaos_base#125] opened 2016-09-02 10:56 UTC
In order to have a more eye candy analog io display, it would be nice to have a gui_style attribute which would be used by UIs to display corresponding icons.

gui_style values could be:
- Temperature
- Humidity
- Pressure
- etc...

**Comment by raoulh** [comment] 2016-09-02 11:27
duplicate of https://github.com/calaos/calaos_base/issues/14

**Closed by raoulh** 2016-09-02 11:27 UTC
Labels: duplicate
